import { Link, useSearchParams } from 'react-router-dom';
import {
  ArrowLeft,
  CheckCircle2,
  CreditCard,
  ShieldCheck,
} from 'lucide-react';

export default function RecoveryDemo() {
  const [params] = useSearchParams();

  const amount = Number(
    params.get('amount') || 0
  );

  const name =
    params.get('name') ||
    'Customer';

  return (
    <div className="min-h-screen bg-rr-bg px-4 py-10 text-rr-text sm:px-6">
      <div className="mx-auto max-w-lg">

        <Link
          to="/triage"
          className="
            inline-flex
            items-center
            gap-2
            text-sm
            text-rr-muted
            hover:text-rr-gold
          "
        >
          <ArrowLeft size={16} />
          Back to Triage Studio
        </Link>

        <div className="mt-8 rr-surface rounded-3xl p-6 sm:p-8">

          <div className="flex items-center gap-3">
            <div
              className="
                grid
                h-10
                w-10
                place-items-center
                rounded-xl
                bg-gradient-to-br
                from-rr-gold
                via-[#B87436]
                to-[#191D2B]
              "
            >
              <CreditCard
                size={19}
                className="text-rr-bg"
              />
            </div>

            <div>
              <div className="font-semibold">
                RazorRescue
              </div>

              <div className="text-xs text-rr-dim">
                Recovery payment
              </div>
            </div>
          </div>

          <div className="mt-8">
            <div className="text-xs uppercase tracking-[0.15em] text-rr-dim">
              Payment recovery
            </div>

            <h1 className="mt-2 text-3xl font-semibold">
              Complete your payment
            </h1>

            <p className="mt-3 text-sm leading-6 text-rr-muted">
              Hello {name}, this demo payment page
              represents the recovery destination
              generated by RazorRescue.
            </p>
          </div>

          <div className="mt-7 rounded-2xl border border-rr-border bg-rr-bg p-5">
            <div className="text-xs text-rr-muted">
              Amount due
            </div>

            <div className="mt-2 text-4xl font-semibold text-rr-gold">
              ₹
              {amount.toLocaleString(
                'en-IN'
              )}
            </div>
          </div>

          <button
            type="button"
            onClick={() => {
              alert(
                'Demo payment completed successfully.'
              );
            }}
            className="
              mt-5
              flex
              w-full
              items-center
              justify-center
              gap-2
              rounded-xl
              bg-rr-gold
              px-5
              py-3.5
              font-semibold
              text-rr-bg
              transition
              hover:bg-rr-goldBright
            "
          >
            Complete demo payment
          </button>

          <div className="mt-5 flex items-center justify-center gap-2 text-xs text-rr-success">
            <ShieldCheck size={14} />
            Secure recovery flow
          </div>

          <div className="mt-6 border-t border-rr-border pt-5 text-center text-xs text-rr-dim">
            <CheckCircle2
              size={14}
              className="mx-auto mb-2 text-rr-success"
            />

            Demo mode — no real payment is processed.
          </div>
        </div>
      </div>
    </div>
  );
}